In [1]:
import numpy as np

In [4]:
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]]) # XOR
n_h = 2
n_x = X.shape[0]
n_y = Y.shape[0]
np.random.seed(1)
W1 = np.random.randn(n_h, n_x)
b1 = np.zeros((n_h, 1))
print(X)
print(W1)
print(b1)

[[0 0 1 1]
 [0 1 0 1]]
[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
[[0.]
 [0.]]


In [3]:
np.dot(W1, X) + b1

array([[ 0.        , -0.61175641,  1.62434536,  1.01258895],
       [ 0.        , -1.07296862, -0.52817175, -1.60114037]])